accounts:
  - name: alice
    coins: ["20000snr", "200000000stake"]
  - name: bob
    coins: ["10000snr", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/blockchain.yaml"
faucet:
  name: bob
  coins: ["50000000snr", "100000000stake"]
build:
  main: "cmd/sonrd"
  binary: "sonrd"
