accounts:
  - name: alice
    coins: ["20000snr", "200000000stake"]
  - name: bob
    coins: ["10000snr", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "internal/blockchain/docs/static/openapi.yml"
  vuex:
    path: "internal/blockchain/vue/src/store"
faucet:
  name: bob
  coins: ["5snr", "100000stake"]
build:
  main: "cmd/sonrd"
  binary: "sonrd"
