version: "3"

services:
  sonr-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/prad/.scnr:/root/.sonr
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - CHAIN_ID=local-1
      - MONIKER=localvalidator
      - KEYRING=test
      - KEY=user1
      - KEY2=user2
      - DENOM=usnr
      - CLEAN=true
      - BLOCK_TIME=5s
    command: "start --pruning=nothing"
    restart: always
    networks:
      - sonr-network

networks:
  sonr-network:
    name: sonr-network
