version: "3"
networks:
  sonr-net:
services:
  node:
    image: sonr-devnet-val
    init: true
    container_name: validator
    networks:
      - sonr-net
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 9090:9090 # grpc
      - 8080:8080 # highway
    restart: always
  faucet:
    image: sonrhq/sonr-faucet:latest
    init: true
    command: ["start", "http://validator:26657"]
    networks:
      - sonr-net
    depends_on:
      - node
    ports:
      - 4500:4500
    restart: always
