version: "3"

services:
  sonr-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/prad/.core:/root/.sonr
    ports:
      - "127.0.0.1:26657:26657"
      - "127.0.0.1:1317:1317"
      - "127.0.0.1:9090:9090"
    environment:
      - CHAIN_ID=local-1
      - MONIKER=localvalidator
      - KEYRING=test
      - KEY=user1
      - KEY2=user2
      - DENOM=usnr
      - CLEAN=true
      - BLOCK_TIME=5s
    command: "start --pruning=nothing"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
