name: sonr-testnet
version: 0.2.20

chains:
  - id: sonr-1
    prettyName: Sonr
    name: custom
    image: ghcr.io/onsonr/sonr:latest
    home: /root/.sonr
    binary: sonrd
    prefix: idx
    denom: usnr
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    coins: 100000000000000usnr,100000000000000snr
    repo: https://github.com/onsonr/sonr
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8001

  - id: osmosis-1
    name: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: hermes-osmo-atom-sonr
    type: hermes
    image: ghcr.io/cosmology-tech/starship/hermes:1.10.0
    replicas: 1
    chains:
      - osmosis-1
      - sonr-1

registry:
  enabled: true
  image: ghcr.io/cosmology-tech/starship/registry:20230614-7173db2
  resources:
    cpu: 0.5
    memory: 200M
