name: sonr-testnet
version: 0.2.20

chains:
  - id: sonr-1
    prettyName: Sonr
    name: custom
    image: ghcr.io/onsonr/sonr:latest
    home: /root/.sonr
    binary: sonrd
    prefix: idx
    denom: usnr
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    coins: 100000000000000usnr,100000000000000snr
    repo: https://github.com/onsonr/sonr
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8001

  - id: osmosis-1
    name: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1319
      rpc: 26659
      faucet: 8009

  - id: evmos-1
    name: evmos
    numValidators: 1
    ports:
      rest: 1312
      rpc: 26652
      faucet: 8002

relayers:
  - name: ibc-relayer
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-4
      - sonr-1
      - evmos-1

explorer:
  enabled: true
  ports:
    rest: 3400

registry:
  enabled: true
  ports:
    rest: 3401
