version: "3.8"

services:
  sonrd.0:
    image: ghcr.io/sonr-io/sonrd:latest
    container_name: sonr-d0
    restart: unless-stopped
    ports:
      - "127.0.0.1:24659:26659"
      - "127.0.0.1:24318:1318"
      - "127.0.0.1:24450:4500"
  highwayd.0:
    build:
      context: ./deploy
      dockerfile: Dockerfile.highwayd
  

