# IP and port of the gRPC server
# port is needed by the server
# ip and port are needed by the clients, so that they know where to contact the server
ip: localhost
port: 7007

# Timeout (in milliseconds) for connections to emmy server
timeout: 5000

# Path to directory with test files
testdata_dir: ./client/testdata

# Absolute path to the folder where secret and public keys are serialized to
# This is used for CSPaillier protocol
# Must exist prior to execution of tests
key_folder: /tmp

# Below are some pre-configured values for bootstrapping specific portocols.
# Several of them are set to values that might not be safe in any real (production) setting.

qr:
  # For safety, you should consider using at least 1024-bit values for p and q.
  p: "109225465622713471254760277521351470678135997982392036687958353565687721648227"
  q: "97677263194688858676678458934032316999260513482681814794753295129431734941099"

schnorr_group:
  p: "16714772973240639959372252262788596420406994288943442724185217359247384753656472309049760952976644136858333233015922583099687128195321947212684779063190875332970679291085543110146729439665070418750765330192961290161474133279960593149307037455272278582955789954847238104228800942225108143276152223829168166008095539967222363070565697796008563529948374781419181195126018918350805639881625937503224895840081959848677868603567824611344898153185576740445411565094067875133968946677861528581074542082733743513314354002186235230287355796577107626422168586230066573268163712626444511811717579062108697723640288393001520781671"
  g: "13435884250597730820988673213378477726569723275417649800394889054421903151074346851880546685189913185057745735207225301201852559405644051816872014272331570072588339952516472247887067226166870605704408444976351128304008060633104261817510492686675023829741899954314711345836179919335915048014505501663400445038922206852759960184725596503593479528001139942112019453197903890937374833630960726290426188275709258277826157649744326468681842975049888851018287222105796254410594654201885455104992968766625052811929321868035475972753772676518635683328238658266898993508045858598874318887564488464648635977972724303652243855656"
  q: "98208916160055856584884864196345443685461747768186057136819930381973920107591"

pseudonymsys:
  org1:
    ecdlog:
      h1x: "111843344654618029419055700569023289100199029635186896671499163057944727230"
      h1y: "63726701293868334061084235330967878003056898720773299094696019482924813137111"
      h2x: "3836882559946612606724713122432195411371871189052450829349314418954131635804"
      h2y: "87187568403836989661029612226711448246955830180833597642485083706252921915098"
      s1: "85369301669043405794894191118963507033301833314658560277996781350824394686629"
      s2: "79942512571124714726300495419426903043602652515054079118036368924839252829692"
    dlog:
      h1: "11253748020267515701977135421640400742511414782332660443524776235731592618314865082641495270379529602832564697632543178140373575666207325449816651443326295587329200580969897900340682863137274403743213121482058992744156278265298975875832815615008349379091580640663544863825594755871212120449589876097254391036951735135790415340694042060640287135597503154554767593490141558733646631257590898412097094878970047567251318564175378758713497120310233239160479122314980866111775954564694480706227862890375180173977176588970220883117212300621045744043530072238840577201003052170999723878986905807102656657527667244456412473985"
      h2: "76168773256070905782197510623595125058465077612447809025568517977679494145178174622864958684725961070073576803345724904501942931513809178875449022568661712955904784104680061168715431907736821341951579763867969478146743783132963349845621343504647834967006527983684679901491401571352045358450346417143743546169924539113192750473927517206655311791719866371386836092309758541857984471638917674114075906273800379335165008797874367104743232737728633294061064784890416168238586934819945486226202990710177343797354424869474259809902990704930592533690341526792158132580375587182781640673464871125845158432761445006356929132"
      s1: "12506074624757438676805734108203754691894440935285828326752482161724637860737614838944853691950924021955680525939780169779888653151633785040698255721224889673095292103687696155341406413918220576785413168329472933244872017244493792250782071009945084029853097333491235700618768793380791519193695496653451014859995982030252835982728985237780700293860028372794252498821615457701308171489000104682637461824347934289263165371702030406332522768141151117618446117035451332086067049461921041400592944133730824346746397649572514314171499080783864209863802530233234409464167893803459953492866757869441725196031561816682693694247"
      s2: "13020332932687210370016553849040757377488575401681932046812877595482551679213287685772359203807696681035708490064843754403752554755544333950653183368282973302817696558827045815163723482995429527843382658004041824178555429087795539456057381420657453502475295608113049300285932123921409924775449579914603546097540511318762759465705188322044741265897435490455892534009820741709256431622346870957086703678859074354841805403651155394020862556084547062880515525275294688441654412852068628826383909174182299298540358523938518798148724428443946911640563994287150550774512490980172141274385123160568136951600563612882876856614"
  ca:
    d: "16249832937458088685598605121372353939294367897674422016342660883663371677076"
    x: "65326558506481070730591115387915499623679021660430456972125964980023301473231"
    y1: "37526396936964061204061100652712760357856013823850948443144488667237183893571"

service_info:
  name: "Anonymous E-Voting system"
  provider: "Government"
  description: "This service verifies your right to vote and allows you to vote electronically with cryptographically assured anonymity"

# the number of attributes must correspond to the CL params (see KnownAttrsNum, 
# CommittedAttrsNum, HiddenAttrsNum)
attributes: {0: "Name, string, true", 1: "Gender, string, true", 2: "Graduated, string, true", 
3: "DateMin, int64, true", 4: "DateMax, int64, true", 5: "Age, int64, false"}

# credentials from which organizations are accepted and which attributes need to be revealed
acceptable_credentials: {"Org1": "Name, DateMin, DateMax", "Org2": "Gender"}
conditions: {3: "greater", 4: "lesser"}
int_values: {3: 1562643000, 4: 1562643000}
#str_values: {0: "Jack"}
str_values: {}

session_key_bytelen: 32

registration_db_address: "localhost:6379"
