name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  run-goreleaser:
    name: "Build All Binaries and Frameworks"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Homebrew w/ cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/foo--*
            ~/Library/Caches/Homebrew/downloads/*--foo-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          brew install FiloSottile/musl-cross/musl-cross
          brew install mingw-w64

      - name: Configure Golang w/ cache
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: ~1.17
      - name: Install dependencies
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
        working-directory: ${{ github.workspace }}/cmd/motor-lib

      - name: Run coverage
        continue-on-error: true
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          version: latest
          args: build --rm-dist --snapshot
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
