name: Generate changelog
on:
  workflow_dispatch:
  release:
    types: [created, edited]

permissions:
  contents: write
  issues: write

jobs:
  generate-changelog:
    runs-on:
      labels: Snorlax
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: sonr-io/core
          ACCESS_TOKEN: ${{secrets.GH_ACTIONS_PAT}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,test:Tests"
          COMMITTER: "Sonr Mind <ai@sonr.io)"
          SUPPRESS_UNSCOPED: true
          REGENERATE_COUNT: 8
