name: New Release  â–¶  Deploy

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  deploy-testnet:
    environment: Testnet
    runs-on: gcp-instance-1
    steps:
      - uses: actions/checkout@v4
      - run: earthly sat wake builder
      - run: task deploy:testnet
        env:
          SONR_TUNNEL_TOKEN: ${{ secrets.SONR_TUNNEL_TOKEN }}
