name: Core Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [release]

  pull_request:
    branches: [release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Runs the `gomobile bind -android` job
  build-android:
    name: "Android AAR  ðŸ”— "

    # Env Variables for the job
    env:
      GO111MODULE: on
      GOMOD: ${{ github.workspace }}/go.mod

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Go Enviornment
      - name: Setup Go Env
        uses: ibrt/golang-github-action@v1
        with:
          go-version: 1.16.6
          go-packages: |
            golang.org/x/mobile/cmd/gomobile

      # Bind Android Framework to Plugin
      - name: Setup and Bind AAR
        run: |
          mkdir -p ${{ github.workspace }}/build/android
          go get golang.org/x/mobile
          gomobile init
          cd ${{ github.workspace }}/bind
          gomobile bind -ldflags='-s -w' -v -target=android -o ${{ github.workspace }}/build/android/io.sonr.core.aar

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: android-aar-releases
          source_dir: "build/android"

  # Runs the `gomobile bind -ios` job
  build-ios:
    name: "iOS Framework  ðŸ”— "

    # Env Variables for the job
    env:
      GO111MODULE: on
      GOMOD: ${{ github.workspace }}/go.mod

    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Go Enviornment
      - name: Setup Go Environment
        uses: ibrt/golang-github-action@v1
        with:
          go-version: 1.16.6
          go-packages: |
            golang.org/x/mobile/cmd/gomobile

      # Bind iOS Framework to Plugin
      - name: Setup and Bind
        run: |
          mkdir -p ${{ github.workspace }}/build/ios
          go get golang.org/x/mobile
          gomobile init
          cd ${{ github.workspace }}/bind
          gomobile bind -ldflags='-s -w' -v -target=ios -bundleid=io.sonr.core -o ${{ github.workspace }}/build/ios/Core.framework

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ios-framework-releases
          source_dir: "build/ios"

  # Runs the `gomobile bind -ios` job
  build-rpc:
    name: "RPC Daemon  ðŸ”¨ "

    # Env Variables for the job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Go Enviornment
      - name: Setup Go Environment
        uses: ibrt/golang-github-action@v1
        with:
          go-version: 1.16.6

      # Build Cmd with Goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ${{ github.workspace }}/cmd
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
