name: Release Workflow

on:
  push:
    tags:
      - v*

jobs:
  release-blockchain:
    name: "Publish Blockchain ðŸ“¢ "
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
      - name: Prepare Release Variables
        id: vars
        uses: tendermint/starport/actions/release/vars@develop

      - name: Issue Release Assets
        uses: ignite-hq/cli/actions/cli@develop
        with:
          args: chain build --release --release.prefix ${{ steps.vars.outputs.tarball_prefix }} -t linux:amd64 -t darwin:amd64

      - name: Create the "latest" Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/release/*.tar.gz"
          replacesArtifacts: false
          name: ${{ steps.vars.outputs.tag_name }}
          token: ${{ secrets.ACTIONS_GH_TOKEN }}
